"""added moves and sections migration

Revision ID: b72ebca069c9
Revises: de42bb4f7df6
Create Date: 2023-09-16 15:41:36.950616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72ebca069c9'
down_revision = 'de42bb4f7df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('successes', sa.Integer(), nullable=True),
    sa.Column('num_puzzles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.Column('move_num', sa.Integer(), nullable=True),
    sa.Column('move', sa.String(length=5), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('mistake', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('explanation', schema=None) as batch_op:
        batch_op.alter_column('puzzle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('move_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('protocol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('move',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=True)

    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.alter_column('fen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('moves',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('theme',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('section',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('theme',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('moves',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('fen',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('explanation', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('move',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('protocol',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('move_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('puzzle_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('move')
    op.drop_table('section')
    # ### end Alembic commands ###
