"""First migration

Revision ID: d1d8aa2c95c7
Revises: 
Create Date: 2023-09-15 22:47:58.894651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d8aa2c95c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('agent_present', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mturk_id', sa.String(length=20), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('task_instance', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['mturk_id'], ['user.mturk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_sections')
    op.drop_table('user_moves')
    op.drop_table('explanations')
    op.drop_table('puzzles')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mturk_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('experiment_completed',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
        batch_op.alter_column('failed_attention_checks',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('consent',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
        batch_op.alter_column('completion_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('protocol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('compensation',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.INTEGER(), nullable=False))
        batch_op.alter_column('compensation',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('protocol',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('completion_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('consent',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('failed_attention_checks',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('experiment_completed',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mturk_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('puzzles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fen', sa.TEXT(), nullable=False),
    sa.Column('moves', sa.TEXT(), nullable=False),
    sa.Column('theme', sa.TEXT(), nullable=False),
    sa.Column('section', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fen'),
    sa.UniqueConstraint('id')
    )
    op.create_table('explanations',
    sa.Column('puzzle_id', sa.INTEGER(), nullable=False),
    sa.Column('move_num', sa.INTEGER(), nullable=False),
    sa.Column('protocol', sa.TEXT(), nullable=False),
    sa.Column('move', sa.TEXT(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.PrimaryKeyConstraint('puzzle_id', 'move_num', 'protocol', 'move')
    )
    op.create_table('user_moves',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('puzzle_id', sa.INTEGER(), nullable=False),
    sa.Column('move_num', sa.INTEGER(), nullable=False),
    sa.Column('section', sa.TEXT(), nullable=False),
    sa.Column('protocol', sa.TEXT(), nullable=False),
    sa.Column('move', sa.TEXT(), nullable=False),
    sa.Column('start_time', sa.INTEGER(), nullable=False),
    sa.Column('start_end', sa.INTEGER(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('mistake', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'start_time')
    )
    op.create_table('user_sections',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('section', sa.TEXT(), nullable=False),
    sa.Column('protocol', sa.TEXT(), nullable=False),
    sa.Column('start_time', sa.INTEGER(), nullable=False),
    sa.Column('end_time', sa.INTEGER(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('num_moves', sa.INTEGER(), nullable=False),
    sa.Column('successes', sa.INTEGER(), nullable=False),
    sa.Column('puzzles', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'section')
    )
    op.drop_table('task')
    op.drop_table('survey')
    op.drop_table('day')
    # ### end Alembic commands ###
