"""Second migration

Revision ID: de42bb4f7df6
Revises: d1d8aa2c95c7
Create Date: 2023-09-16 08:24:14.993222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de42bb4f7df6'
down_revision = 'd1d8aa2c95c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
